add `ci` directory
ONSdigital/dp-cache pull request #2
Opened 2022-07-12 12:31 UTC by justinpjose

### What
**Describe what you have changed and why.**
- add `ci` directory

### How to review
**Describe the steps required to test the changes.**
- Check if the code changes make sense

### Who can review
**Describe who worked on the changes, so that other people can review.**
- Anyone

2022-07-12 18:36 UTC, cookel2 requested changes
Some of the files are missing new lines at the end.

2022-07-12 18:36 UTC, cookel2 commented on ci/audit.yml
> +  path: dp-cache/ci/scripts/audit.sh
new line needed

2022-07-13 08:23 UTC, justinpjose commented on ci/audit.yml
> +  path: dp-cache/ci/scripts/audit.sh
Done

2022-07-13 08:23 UTC, justinpjose commented on ci/scripts/build.sh
> +popd
Done

2022-07-13 08:23 UTC, justinpjose commented on ci/scripts/unit.sh
> +popd
Done

2022-07-13 08:29 UTC, cookel2 approved these changes
looks good to me

2022-07-13 08:31 UTC, merged